version: '3'
services:
  beanstalkd_exporter:
    build:
      context: .
    command:
      - -beanstalkd.address=beanstalkd:11300
    links:
      - beanstalkd
    ports:
      - "8080:8080"
  beanstalkd:
    image: schickling/beanstalkd
